name: Checkpatch

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  patch_check:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4

      - name: Install Perl
        run: |
          sudo apt-get update
          sudo apt-get install -y perl

      - name: Run checkpatch
        working-directory: ${{ github.workspace }}
        run: |
          chmod +x ./scripts/run_checkpatch.sh
          ./scripts/run_checkpatch.sh
